version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    image: wa-api:latest
    ports:
      - "8081:3001"
    volumes:
      - ./.wwebjs_auth:/.wwebjs_auth
    environment:
      - NODE_ENV=development
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
    command: npm start

