version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - WHATSAPP_API_KEY=YOUR_API_KEY
    command: npm start
