version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - WHATSAPP_API_KEY=YOUR_API_KEY
    command: npm start
